// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXt4LgppRQrMyJ8CXttqJe6WO0TxhdY44',
    appId: '1:1017652814636:web:90c26b6c8e5e0abded4289',
    messagingSenderId: '1017652814636',
    projectId: 'probar-ejemplo',
    authDomain: 'probar-ejemplo.firebaseapp.com',
    storageBucket: 'probar-ejemplo.firebasestorage.app',
    measurementId: 'G-16J95C939X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLXNcy3eTOTc2HkoCVuVcOUv3Hk2OqAFw',
    appId: '1:1017652814636:android:b9b251ad716380c4ed4289',
    messagingSenderId: '1017652814636',
    projectId: 'probar-ejemplo',
    storageBucket: 'probar-ejemplo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGgPRwGW1xT5Nl3egwzoA2MNH3fXJM9gc',
    appId: '1:1017652814636:ios:e984282fd15c355fed4289',
    messagingSenderId: '1017652814636',
    projectId: 'probar-ejemplo',
    storageBucket: 'probar-ejemplo.firebasestorage.app',
    iosBundleId: 'com.example.persistenciaDatos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGgPRwGW1xT5Nl3egwzoA2MNH3fXJM9gc',
    appId: '1:1017652814636:ios:e984282fd15c355fed4289',
    messagingSenderId: '1017652814636',
    projectId: 'probar-ejemplo',
    storageBucket: 'probar-ejemplo.firebasestorage.app',
    iosBundleId: 'com.example.persistenciaDatos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXt4LgppRQrMyJ8CXttqJe6WO0TxhdY44',
    appId: '1:1017652814636:web:03bc13b7ca5714dced4289',
    messagingSenderId: '1017652814636',
    projectId: 'probar-ejemplo',
    authDomain: 'probar-ejemplo.firebaseapp.com',
    storageBucket: 'probar-ejemplo.firebasestorage.app',
    measurementId: 'G-5SZ3J87L0V',
  );
}
