// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi1O2rZt9rNEnrVT1Zd2Mr-lVfF3HzSlQ',
    appId: '1:590540999041:web:48d5916492ad2b09d50080',
    messagingSenderId: '590540999041',
    projectId: 'practica-2-desde-0',
    authDomain: 'practica-2-desde-0.firebaseapp.com',
    storageBucket: 'practica-2-desde-0.firebasestorage.app',
    measurementId: 'G-W3C0ZXGDMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-igtksKTyIZRVjeYlFAGugBTzZrmLGY',
    appId: '1:590540999041:android:df8e8f8cbef0813dd50080',
    messagingSenderId: '590540999041',
    projectId: 'practica-2-desde-0',
    storageBucket: 'practica-2-desde-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyReS7MPZCzPE6SEBuk9xEzOJbhhGXB5E',
    appId: '1:590540999041:ios:843fe0dbf127085cd50080',
    messagingSenderId: '590540999041',
    projectId: 'practica-2-desde-0',
    storageBucket: 'practica-2-desde-0.firebasestorage.app',
    iosBundleId: 'com.example.practica2Desde0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyReS7MPZCzPE6SEBuk9xEzOJbhhGXB5E',
    appId: '1:590540999041:ios:843fe0dbf127085cd50080',
    messagingSenderId: '590540999041',
    projectId: 'practica-2-desde-0',
    storageBucket: 'practica-2-desde-0.firebasestorage.app',
    iosBundleId: 'com.example.practica2Desde0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi1O2rZt9rNEnrVT1Zd2Mr-lVfF3HzSlQ',
    appId: '1:590540999041:web:800651a046f8660ed50080',
    messagingSenderId: '590540999041',
    projectId: 'practica-2-desde-0',
    authDomain: 'practica-2-desde-0.firebaseapp.com',
    storageBucket: 'practica-2-desde-0.firebasestorage.app',
    measurementId: 'G-S35K6CC9QR',
  );
}
