// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn05BD0zkbI7NDsTc2dJQz85PyNGXsYlA',
    appId: '1:402431994963:web:5ae0c4d0a5bfcce72a6aa6',
    messagingSenderId: '402431994963',
    projectId: 'prueba-persistencia-datos-1',
    authDomain: 'prueba-persistencia-datos-1.firebaseapp.com',
    storageBucket: 'prueba-persistencia-datos-1.firebasestorage.app',
    measurementId: 'G-72F0P99S50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8eT_kGPMN28uoWixRQQRMt3RA1OqKL6A',
    appId: '1:402431994963:android:3961847911dced1d2a6aa6',
    messagingSenderId: '402431994963',
    projectId: 'prueba-persistencia-datos-1',
    storageBucket: 'prueba-persistencia-datos-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUYVUAhTCLvU4pXw_WPUE5CT0KFbV4tjs',
    appId: '1:402431994963:ios:715255e3315a242d2a6aa6',
    messagingSenderId: '402431994963',
    projectId: 'prueba-persistencia-datos-1',
    storageBucket: 'prueba-persistencia-datos-1.firebasestorage.app',
    iosBundleId: 'com.example.loginHabitsSwitch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUYVUAhTCLvU4pXw_WPUE5CT0KFbV4tjs',
    appId: '1:402431994963:ios:715255e3315a242d2a6aa6',
    messagingSenderId: '402431994963',
    projectId: 'prueba-persistencia-datos-1',
    storageBucket: 'prueba-persistencia-datos-1.firebasestorage.app',
    iosBundleId: 'com.example.loginHabitsSwitch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn05BD0zkbI7NDsTc2dJQz85PyNGXsYlA',
    appId: '1:402431994963:web:45846579fde8cfbd2a6aa6',
    messagingSenderId: '402431994963',
    projectId: 'prueba-persistencia-datos-1',
    authDomain: 'prueba-persistencia-datos-1.firebaseapp.com',
    storageBucket: 'prueba-persistencia-datos-1.firebasestorage.app',
    measurementId: 'G-BDDFZ8R8CG',
  );
}
