// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbfA-X-mlFm0P_Sl8D-lR8_h0il_XLXHM',
    appId: '1:706054864655:web:fba8462d0180689832c87a',
    messagingSenderId: '706054864655',
    projectId: 'fir-ejercicio-crud',
    authDomain: 'fir-ejercicio-crud.firebaseapp.com',
    storageBucket: 'fir-ejercicio-crud.firebasestorage.app',
    measurementId: 'G-JR13KXB29J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ZFRvmrtA22ujj8geX5ptC7BazN6xjhY',
    appId: '1:706054864655:android:e48e4493b5db82d032c87a',
    messagingSenderId: '706054864655',
    projectId: 'fir-ejercicio-crud',
    storageBucket: 'fir-ejercicio-crud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZNDUJ6DoyWLIo_twGHXJMkF4_YJkZ4Rc',
    appId: '1:706054864655:ios:7bad60772d32a6a332c87a',
    messagingSenderId: '706054864655',
    projectId: 'fir-ejercicio-crud',
    storageBucket: 'fir-ejercicio-crud.firebasestorage.app',
    iosBundleId: 'com.example.persistenciaDatosEjercicios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZNDUJ6DoyWLIo_twGHXJMkF4_YJkZ4Rc',
    appId: '1:706054864655:ios:7bad60772d32a6a332c87a',
    messagingSenderId: '706054864655',
    projectId: 'fir-ejercicio-crud',
    storageBucket: 'fir-ejercicio-crud.firebasestorage.app',
    iosBundleId: 'com.example.persistenciaDatosEjercicios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbfA-X-mlFm0P_Sl8D-lR8_h0il_XLXHM',
    appId: '1:706054864655:web:51f6e382f8d4c21332c87a',
    messagingSenderId: '706054864655',
    projectId: 'fir-ejercicio-crud',
    authDomain: 'fir-ejercicio-crud.firebaseapp.com',
    storageBucket: 'fir-ejercicio-crud.firebasestorage.app',
    measurementId: 'G-78ESLBF07C',
  );
}
